import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./grid-fixes.css";
import "./safari-fixes.css";
import "./safari-gallery-fixes.css";
import "./lightbox-fixes.css";

const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-inter",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${inter.variable} font-sans antialiased`}
				suppressHydrationWarning>
				{children}
			</body>
		</html>
	);
}
